# Generated by Django 3.1 on 2021-08-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
